### ISSUE TITLE
How to build the PhIPData?

### ISSUE THREAD

**Issue by MSTU1995** [athchen/beer_manuscript#1]
I found it very difficult to construct PhIPData.
When applying to a new project, how to build PhIPData easily? Is there a function available?

**Comment by athchen** [comment]
Yes -- there is an easy constructor to create a `PhIPData` object. Please see the vignette [here](https://www.bioconductor.org/packages/release/bioc/vignettes/PhIPData/inst/doc/PhIPData.html) for details and examples.
